<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'About' => 'Tentang Kami',
    'Access Menu' => '',
    'Action Menu' => '',
    'Administration Menu' => '',
    'All rights reserved' => '',
    'Application List' => '',
    'Are you sure you want to delete this item?' => '',
    'Auth Key' => '',
    'Change Password' => '',
    'Contact' => '',
    'Copyright' => '',
    'Create' => '',
    'Create Role' => '',
    'Create Roles' => '',
    'Create User' => '',
    'Created At' => '',
    'Dashboard' => '',
    'Definition' => '',
    'Delete' => '',
    'E-Promosi' => '',
    'E-Status' => '',
    'Email' => '',
    'Fullname' => '',
    'Groupname' => '',
    'Home' => 'Laman Utama',
    'ID' => '',
    'Incorrect username or password.' => '',
    'Is Admin' => '',
    'Last Login' => '',
    'Last Login Attempts' => '',
    'Last Login: ' => '',
    'List Roles' => '',
    'List Users' => '',
    'Login' => 'Daftar Masuk',
    'Login Attempts' => '',
    'Manage Role' => '',
    'Manage User' => '',
    'Name' => '',
    'New Role' => '',
    'New User' => '',
    'Opensoft Technologies Sdn Bhd' => '',
    'Password Hash' => '',
    'Password Reset Token' => '',
    'Password reset for ' => '',
    'Payment Receipt' => '',
    'Phone' => '',
    'Profile' => '',
    'Register Date' => '',
    'Reset' => '',
    'Role ID' => '',
    'Roles' => '',
    'Search' => '',
    'Sign In' => '',
    'Sign in' => '',
    'Sign in to start your session' => '',
    'Sign out' => '',
    'Site Lang' => '',
    'Status' => '',
    'The above error occurred while the Web server was processing your request.
                Please contact us if you think this is a server error. Thank you.
                Meanwhile, you may <a href="{homeUrl}">return to dashboard</a> or try using the search
                form.' => '',
    'There is no user with such email.' => '',
    'Update' => '',
    'Update Date' => '',
    'Update {modelClass} ' => '',
    'Update {modelClass}: ' => '',
    'Updated At' => '',
    'User Account Menu' => '',
    'User ID' => '',
    'Username' => '',
    'Users' => '',
    'View Role' => '',
    'View User' => '',
    'Withdrawal' => '',
];
